server:
  port: 8081
  servlet:
    context-path: /demo
jwt:
  secret: gvfkld;v458frefrcre841552ewefre545632rerf
  lifetime: 10m
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/auth-db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true