version: '3.9'
services:

  productdb:
    image: postgres:latest
    container_name: product-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productdb
    expose:
      - 5430
    ports:
      - 5430:5432
    restart: always

  order-db:
    image: postgres:latest
    container_name: order-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order-db
    expose:
      - 5435
    ports:
      - 5435:5432
    restart: always

  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth-db
    expose:
      - 5434
    ports:
      - 5434:5432
    restart: always

  reviewdb:
    image: postgres:latest
    container_name: review-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reviewdb
    expose:
      - 5433
    ports:
      - 5433:5432
    restart: always

  #product
  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://productdb:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8080:8080

  #Auth
  auth-service:
    build: ./auth-service
    container_name: auth-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8081:8080

  #Order
  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/order-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8082:8080

  # Отзывы
  review-service:
    build: ./review-service
    container_name: review-service-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://reviewdb:5432/reviewdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8000:8080

  api-gateway:
    ports:
      - "8090:8090"
    build: ./api-gateway
    container_name: api-gateway-container

networks:
  db:
    driver: bridge