version: '1'
services:
  auth-service:
    build: auth-service
    container_name: auth-service-container
    ports:
      - "8081:8081"
  product-service:
    build: ./product-service
    container_name: product-service-container
    ports:
      - "8082:8082"
  order-service:
    build: ./order-service
    container_name: order-service-container
    ports:
      - "8083:8083"
  review-service:
    build: ./review-service
    container_name: review-service-container
    ports:
      - "8084:8084"
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway-container
    ports:
      - "8080:8080"