spring:
  datasource:
    Driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/auth-db
    username: postgres
    password: DB_PASSWORD:postgres
  liquibase:
    change-log: classpath:changelog-master.yaml
    enabled: true
    drop-first: false