server:
  port: 8083
  servlet:
    context-path: /product-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres1
    username: postgres
    password: 6706598
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: product_db
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true