spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reviews_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123123}
  liquibase:
    change-log: classpath:changelog-master.yaml
    enabled: true
    drop-first: false